# version: '2'
volumes:
  data:

services:
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
  main:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile
    # volumes:
    #     - "./:/app"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=TRUE
    command: python main.py
    depends_on:
      - redis
