# version: '2'
volumes:
  data:

services:
  redis:
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - data:/data
    # ports:
    #   - 6379:6379
  main:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile
    # volumes:
    #     - "./:/app"
    environment:
      - REDIS_URL=redis://redis
      - PYTHONUNBUFFERED=TRUE
    command: python main.py
    networks:
      - redis_network
    depends_on:
      - redis
networks:
  redis_network:
